[package]
name = "desktop-tool"
version = "0.1.0"
edition = "2021"

[dependencies]
merge = "0.1.0"
nix = { version = "0.29.0", features = ["process"] }
serde = { version = "1.0", features = ["derive"] }
toml = { version = "0.8.19" }
